on:
  push:
    branches:
      - main
jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: npm install -g lerna
      - run: lerna bootstrap
      - run: lerna run prepack
      - run: cd docs && yarn install && yarn build
      - run: yarn sui deploy --compiled-build --dir="docs/dist" --prod
